// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cvVrHCaBNnM9EFuM3lAtpfCG2Za_kOc',
    appId: '1:347630935812:web:0a0e7689a0e7e9d59b3a51',
    messagingSenderId: '347630935812',
    projectId: 'violeafybasket',
    authDomain: 'violeafybasket.firebaseapp.com',
    storageBucket: 'violeafybasket.firebasestorage.app',
    measurementId: 'G-CNWTGY929K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLH5QqLLlw415y94GPl-TJjtMsapkwYs',
    appId: '1:347630935812:android:debe09fb5de0aed29b3a51',
    messagingSenderId: '347630935812',
    projectId: 'violeafybasket',
    authDomain: 'violeafybasket.firebaseapp.com',
    storageBucket: 'violeafybasket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd0YImMmU4zDVh1HXzh7-ZMGxV8B2Xg90',
    appId: '1:347630935812:ios:ef88c0ec60bf97b39b3a51',
    messagingSenderId: '347630935812',
    projectId: 'violeafybasket',
    storageBucket: 'violeafybasket.firebasestorage.app',
    androidClientId: '347630935812-ph9h2ftc9itd88edqd7kufj6gc2hbv90.apps.googleusercontent.com',
    iosClientId: '347630935812-qmon0p29695a98g2l974it49d5vqdruo.apps.googleusercontent.com',
    iosBundleId: 'com.leafy.webapp.leafyWebapp',
  );
}
